name: basemail

services:
  mongo:
    image: mongodb/mongodb-community-server:7.0.8-ubi8
    restart: unless-stopped
    # todo: add mongo credentials and authorize api calls
    # this is bad but i don't want to create a mongo user on my system
    user: root
    volumes:
      - auth-data:/data/db
    ports:
      - 27017:27017

  mongo-init:
    image: ghcr.io/basemail/auth-server:latest
    network_mode: 'host'
    depends_on:
      - mongo
    restart: no
    environment:
      ENVIRONMENT: test
    entrypoint:
      - ./admin
      - init-db

  auth-server:
    image: ghcr.io/basemail/auth-server:latest
    # todo: stop hardcoding localhost
    network_mode: 'host'
    depends_on:
      - mongo
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ENVIRONMENT: local
      JWT_SECRET: ${JWT_SECRET?set JWT_SECRET in your .env file}
    entrypoint:
      - ./api

  mail-server:
    image: ghcr.io/basemail/mail-server:latest
    network_mode: 'host'
    restart: unless-stopped
    environment:
      AUTH_API_URL: http://localhost:8081
      CHAIN_ID: 84532
      RPC_URL: ${RPC_URL}
      BASEMAIL_ADDRESS: 0xBdB578684B46ef9FdB669A49c2d19E2F96d7920F
    ports:
      - 8080:8080
    depends_on:
      - auth-server

networks:
  basemail-backend:

volumes:
  auth-data:
